### ISSUE TITLE
AddressSanitizer: SEGV src/ast/validate.cc:49 in re2c::validate_ast(std::vector<re2c::spec_t, std::allocator<re2c::spec_t> > const&, bool)

### ISSUE THREAD

**Issue by fgeek** [skvadrik/re2c#227]
Tested commit: c432c5c34c60a9e450714a7d1d5c39b34c9fd0a0
Tools: [american fuzzy lop](http://lcamtuf.coredump.cx/afl/) 2.52b, [afl-utils](https://gitlab.com/rc0r/afl-utils)
[re2c-2018-11-04-001.zip](https://github.com/skvadrik/re2c/files/2545647/re2c-2018-11-04-001.zip)
```
ASAN:DEADLYSIGNAL
=================================================================
==16818==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x5585338c21d4 bp 0x7fff26ad70f0 sp 0x7fff26ad7080 T0)
    #0 0x5585338c21d3 in re2c::validate_ast(std::vector<re2c::spec_t, std::allocator<re2c::spec_t> > const&, bool) src/ast/validate.cc:49
    #1 0x558533823362 in re2c::compile(re2c::Scanner&, re2c::Output&, re2c::Opt&) src/compile.cc:165
    #2 0x55853361c5f9 in main src/main.cc:31
    #3 0x7f5b809ea2e0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202e0)
    #4 0x55853361d709 in _start (/home/afl/builds/re2c/c432c5c34c60a9e450714a7d1d5c39b34c9fd0a0/bin/re2c+0x1e709)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV src/ast/validate.cc:49 in re2c::validate_ast(std::vector<re2c::spec_t, std::allocator<re2c::spec_t> > const&, bool)
==16818==ABORTING
```
```
(gdb) list
44          }
45
46          if (!cflag) {
47              for (i = b; i != e; ++i) {
48                  if (i->name != "") {
49                      fatal_l(i->rules[0].code->fline,
50                          "conditions are only allowed with '-c', '--conditions' option");
51                  }
52              }
53          } else {
```

**Comment by skvadrik** [comment]
Confirmed, minimized example is:
```
/*!re2c
    <c> * {}
*/
```

**Comment by skvadrik** [comment]
@fgeek Should be fixed by this commit: https://github.com/skvadrik/re2c/commit/e566a24ae79cae87e37d947ae5f201307b315b99.

**Comment by fgeek** [comment]
Confirmed. Thank you!
