### ISSUE TITLE
re2c hangs if posix-captvars is used

### ISSUE THREAD

**Issue by eilvelia** [skvadrik/re2c#519]
Using `examples/c/submatch/03_captures.re` with `posix-captvars` instead of `captvars`:

```c
// re2c $INPUT -o $OUTPUT
#include <assert.h>
#include <stddef.h>

typedef struct { int major, minor, patch; } SemVer;

static int s2n(const char *s, const char *e) { // pre-parsed string to number
    int n = 0;
    for (; s < e; ++s) n = n * 10 + (*s - '0');
    return n;
}

static int lex(const char *str, SemVer *ver) {
    const char *YYCURSOR = str, *YYMARKER;

    // Final tag variables available in semantic action.
    /*!svars:re2c format = 'const char *@@;\n'; */

    // Intermediate tag variables used by the lexer (must be autogenerated).
    /*!stags:re2c format = 'const char *@@;\n'; */

    /*!re2c
        re2c:yyfill:enable = 0;
        re2c:define:YYCTYPE = char;
        re2c:posix-captvars = 1;

        num = [0-9]+;

        (num) "." (num) ("." num)? [\x00] {
            (void) yytl0; (void) yytr0; // some variables are unused
            ver->major = s2n(yytl1, yytr1);
            ver->minor = s2n(yytl2, yytr2);
            ver->patch = yytl3 ? s2n(yytl3 + 1, yytr3) : 0;
            return 0;
        }
        * { return 1; }
    */
}

int main() {
    SemVer v;
    assert(lex("23.34", &v) == 0 && v.major == 23 && v.minor == 34 && v.patch == 0);
    assert(lex("1.2.999", &v) == 0 && v.major == 1 && v.minor == 2 && v.patch == 999);
    assert(lex("1.a", &v) == 1);
    return 0;
}
```

results in re2c hanging with 100% CPU and continously increasing memory consumption.

`posix-captures` appears to work. In the `04_posix_captures.re` example, if `re2c:posix-captures = 1;` is replaced with `re2c:posix-captvars = 1;`, the same issue appears.

```
Samples: 127K of event 'cycles:P', 4000 Hz, Event count (approx.): 55979926855 lost: 0/0 drop: 0/0                                                                                   
Overhead  Shared Object        Symbol                                                                                                                                                
  19.78%  libc.so.6            [.] __memcmp_avx2_movbe                                                                                                                               
  18.76%  re2ocaml             [.] std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<c
   3.41%  re2ocaml             [.] re2c::captvar_name[abi:cxx11](unsigned long, re2c::opt_t const*)                                                                                  
   3.27%  re2ocaml             [.] memcmp@plt  
```

```
(gdb) bt full
#0  0x00007f787f8628d9 in __memcmp_avx2_movbe ()
   from /nix/store/wn7v2vhyyyi6clcyn0s9ixvl7d4d87ic-glibc-2.40-36/lib/libc.so.6
No symbol table info available.
#1  0x0000000000426878 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::_Identity<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_M_get_insert_unique_pos(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
No symbol table info available.
#2  0x0000000000455dbb in re2c::Adfa::calc_stats(re2c::OutputBlock&) ()
No symbol table info available.
#3  0x000000000040a21a in re2c::compile(int, char**) [clone .isra.0] ()
No symbol table info available.
#4  0x0000000000408c9c in main ()
No symbol table info available.
```

(note: these were run on different code.)

**Comment by skvadrik** [comment]
Thanks! Fixed in https://github.com/skvadrik/re2c/commit/2b80343e4dd273e3e0c22c6e0c1709e5d3f49a62.
